### ISSUE TITLE
silock.c:(.text+0x184): undefined reference to `Silo_version_4_11'

### ISSUE THREAD

**Issue by yurivict** [LLNL/Silo#286]
Build breaks:
```
--- CMakeFiles/silock.dir/all ---
/usr/local/bin/ld: CMakeFiles/silock.dir/tools/silock/silock.c.o: in function `main':
silock.c:(.text+0x184): undefined reference to `Silo_version_4_11'
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** [bin/silock] Error code 1
```

clang-14
revision 4.11-68-g819658e
FreeBSD 13.1

**Comment by markcmiller86** [comment]
I feel like you may be building from 4.11RC but still using 4.11 release headers.

**Comment by yurivict** [comment]
Indeed, Silo conflicts with its own headers from the previous release.

**Comment by bhuloka** [comment]
Is there any workaround?

**Comment by markcmiller86** [comment]
You can work-around the issue yourself by defining the unresolved external (an `int`) that it is looking for. That said, this kind of compile-time breakage is intentional especially when I am not 100% confident that all commits since prev. release did not change more than just *implementation*. I/we don't support mixing versions of Silo headers and libraries.
